# Generated by Django 2.1.3 on 2018-11-23 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('known_as', models.CharField(blank=True, default='', max_length=30)),
                ('acronym', models.CharField(blank=True, default='', max_length=30)),
                ('parent_organisation', models.CharField(blank=True, default='', max_length=50)),
                ('registration_number', models.CharField(blank=True, default='', max_length=60)),
                ('iat_uid', models.CharField(blank=True, default='', max_length=255)),
                ('address_1', models.CharField(default='', max_length=255)),
                ('address_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(default='', max_length=30)),
                ('province', models.CharField(blank=True, default='', max_length=30)),
                ('zip', models.CharField(blank=True, default='', max_length=15)),
                ('po_box', models.CharField(blank=True, default='', max_length=30)),
                ('landmark', models.CharField(blank=True, default='', max_length=30)),
                ('size', models.CharField(blank=True, choices=[('0-10', '0 - 10'), ('11-50', '11 - 50'), ('51-250', '51 - 250'), ('250+', '250+')], default='', max_length=30)),
                ('annual_expenditure', models.CharField(blank=True, choices=[('0-20K', 'USD < 20K'), ('20K-100K', 'USD 20K - 100K'), ('100K-500K', 'USD 100K - 500K'), ('500K-5M', 'USD 500K - 5M'), ('5M-100M', 'USD 5M - 100M'), ('100M+', 'USD >100M')], default='', max_length=30)),
                ('website', models.URLField(blank=True, default='', max_length=100)),
                ('social_media', models.URLField(blank=True, default='', max_length=100)),
                ('other_social_media', models.URLField(blank=True, default='', max_length=100)),
                ('biography', models.TextField(blank=True, default='')),
                ('terms_acceptance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('privacy_acceptance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_mobile', models.CharField(max_length=15)),
                ('job_role', models.CharField(default='', max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organisation')),
            ],
        ),
    ]
