# Generated by Django 2.1.3 on 2018-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organisationtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='sort_order',
            field=models.IntegerField(default=''),
        ),
    ]
