# Generated by Django 2.1.3 on 2018-11-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181123_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtype',
            name='sort_order',
            field=models.CharField(default='', max_length=20),
        ),
    ]
