# Generated by Django 2.1.3 on 2018-11-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181123_0811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationType',
        ),
    ]
