# Generated by Django 2.1.3 on 2018-11-27 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_organisationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='privacy_acceptance_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 14, 14, 289107, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='terms_acceptance_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 14, 14, 289086, tzinfo=utc)),
        ),
    ]
