# Generated by Django 2.1.3 on 2018-11-27 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181127_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='privacy_acceptance_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 23, 11, 705914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='terms_acceptance_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 10, 23, 11, 705893, tzinfo=utc)),
        ),
    ]
