# Generated by Django 2.1.3 on 2018-11-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentpackage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='number_included',
            field=models.IntegerField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=9),
        ),
    ]
