# Generated by Django 2.1.3 on 2018-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0002_auto_20181128_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpackage',
            name='number_included',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='assessmentpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
