# Generated by Django 2.1.3 on 2018-11-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0003_auto_20181128_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='number_included',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='price',
        ),
    ]
