# Generated by Django 2.1.3 on 2018-11-29 07:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('number', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('level', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')])),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('upload_type', models.CharField(blank=True, choices=[('policy', 'Policy'), ('procedure', 'Procedure'), ('process', 'Process')], max_length=255)),
                ('reference', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyArea')),
            ],
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='survey.SurveySection'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
