# Generated by Django 2.1.3 on 2018-11-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181127_1023'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('submitted', models.DateTimeField(editable=False, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], verbose_name='target tier')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organisation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.Survey')),
            ],
        ),
    ]
