# Generated by Django 2.1.3 on 2018-12-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
